logging:
  level:
    org:
      springframework: INFO
server:
  context-path: /api
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/webledger'
    username: webledger
    password: z4heFE
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  session:
    store-type: jdbc
webledger:
  security:
    enabled: true
    login-url: http://localhost:4200/login
    success-url: http://localhost:4200/
#---
#spring:
  #profile: prod
  #datasource:
    #url: 'jdbc:postgresql://172.19.0.1:5432/webledger'
    #username: webledger
    #password: z4heFE
